### ISSUE TITLE
rpi-rt-kernel on Rpi3 Model B+ not works

### ISSUE THREAD

**Issue by MattiaDeiRossi** [remusmp/rpi-rt-kernel#12]
Hi all, 

I tried to follow your Readme.md file to install raspbian rt on RPI b3+, but the boot fails with error 
```
INFO: rcu_preempt detected stalls on CPUs/tasks:
```

do you have any suggestions?

**Comment by gboddaer** [comment]
I can confirm the issue. Also before using this github, I tried to build the real-time kernel myself following this ( https://gist.github.com/G-UK/196638656e822a2b67f7843db875646d ) recipe. The patch and build succeeds, but those more recent kernels will not run either (they start to boot but fail om MMC or USB access). Maybe they would boot successfully by setting some extra CONFIG or by fixing the respective drivers. I was hoping somebody else already fixed the problem. Unfortunately, this rpi-rt-kernel recipe does not work for the pi-3B+ as well. However, it does work for the PI4B. But I was trying to get some latency numbers for the 4xA53 as used in the PI3.

**Comment by remusmp** [comment]
Unfortunately I don't have a pi3 right now to debug the issue. I'll ask some former colleagues and try to get one somewhere mid June. Hopefully they still have some stashed somewhere.

**Comment by remusmp** [comment]
One first issue I noticed is that we need to use bcm2709 for pi3b+:
`make bcm2709_defconfig`

![image](https://github.com/remusmp/rpi-rt-kernel/assets/3688493/eeecf82f-4d53-4055-ac6a-4c1a0280d9ad)

There might be other issues. You may try the above if you can test quickly.

**Comment by gboddaer** [comment]
I did not try yet for the rpi-rt-kernel, but I found a combination that works for the PI3B+ here:  https://github.com/kdoren/linux/archive/refs/tags/5.10.35-rt39.tar.gz
Indeed only in 32-bit mode.
reference: https://github.com/kdoren/linux
I tried again to build myself and test for 6.1.29-rt10-v7l+ but fails also for PI3B+, works for PI4B.

**Comment by remusmp** [comment]
I have made some changes and it should build properly now for all platforms. Try `make Pi3` and let me know if you still encounter issues. I'll try to get a Pi3 from somewhere to debug if it's still an issue.
