### ISSUE TITLE
docker: No such file or directory

### ISSUE THREAD

**Issue by ryanGT** [remusmp/rpi-rt-kernel#13]
I am new to kernel compiling and trying a different options to compile an RT kernel.

I clone the repo , cd-ed into it and then typed make.  I get the following error:

~/rpi-rt-kernel$ make
rm -fr build
make build raspios_image_name=raspios_lite_arm64
make[1]: Entering directory '/home/drkrauss/rpi-rt-kernel'
mkdir -p build
docker build --build-arg PLATFORM32= --build-arg RASPIOS_IMAGE_NAME=raspios_lite_arm64 -t rpi-rt-linux .
make[1]: docker: No such file or directory
make[1]: *** [Makefile:16: build] Error 127
make[1]: Leaving directory '/home/drkrauss/rpi-rt-kernel'
make: *** [Makefile:6: all] Error 2

If it matters, I am not cross-compiling (I don't think).  I am running this from an RPi.

Any help would be appreciated.

Thanks,
Ryan

**Comment by remusmp** [comment]
Hi Ryan,

You need `docker` in order to build the sd card image. The `No such file or directory` refers to the fact that you don't have `docker` installed (the `docker` executable is not found). You may build the sd card image from you personal computer and not from the pi because it cross-compiles for the pi.

Regards,
R.

**Comment by ryanGT** [comment]
Thanks.  So, if I tried it from my mac, using homebrew, any ideas what I need to install?

Thanks again,
Ryan

**Comment by ryanGT** [comment]
Current plan is to try this:

brew install arm-linux-gnueabihf-binutils llvm rsync

followed by

brew install docker

and see if I can make.

Regards,
Ryan

**Comment by remusmp** [comment]
Only `docker` and `make`. The purpose of using `docker` is to package all necessary tools inside the container such that you don't need to install them on your host machine.

**Comment by ryanGT** [comment]
Apparently, docker on mac is tricky:

https://stackoverflow.com/questions/44084846/cannot-connect-to-the-docker-daemon-on-macos

**Comment by ryanGT** [comment]
I guess my next move is to try Ubuntu in a VirtualBox.  I will see what happens.

I have an old Ubuntu machine laying around, but I think it is running something like 16.04 LTS or something insanely old.

**Comment by ryanGT** [comment]
docker doesn't seem to work in my virtualbox ubuntu.  I tried installing the official docker based on instructions here:
https://docs.docker.com/desktop/install/ubuntu/.  When I try to lauch docker desktop, I get an error about KVM not being enabled.
