### ISSUE TITLE
Cannot build image for PiZero

### ISSUE THREAD

**Issue by houserockr** [remusmp/rpi-rt-kernel#14]
When I try to build an image for `PiZero` I get this:

```
$ make PiZero
<snip>
=> => writing image sha256:8bde01b7089c0e8d7920e2f5284666b73743c281e5cb4b0f03dbc33d252008d6                                                                   0.0s
 => => naming to docker.io/library/rpi-rt-linux                                                                                                                0.0s
docker rm tmp-rpi-rt-linux || true
Error: No such container: tmp-rpi-rt-linux
docker run --privileged --name tmp-rpi-rt-linux rpi-rt-linux /raspios/build.sh
  INSTALL /raspios/mnt/disk/lib/modules/5.15.92-rt68+/kernel/arch/arm/crypto/aes-arm.ko
  XZ      /raspios/mnt/disk/lib/modules/5.15.92-rt68+/kernel/arch/arm/crypto/aes-arm.ko.xz
<snip>
  INSTALL /raspios/mnt/disk/lib/modules/5.15.92-rt68+/kernel/net/sched/cls_rsvp.ko
  XZ      /raspios/mnt/disk/lib/modules/5.15.92-rt68+/kernel/net/sched/cls_rsvp.ko.xz
  INSTALL /raspios/mnt/boot/bcm2835-rpi-zero-w.dtb
/raspios
cp: cannot stat '/rpi-kernel/linux/arch/arm/boot/zImage': No such file or directory
  adding: 2023-05-03-raspios-bullseye-armhf-lite.img (deflated 71%)
docker cp tmp-rpi-rt-linux:/raspios/build/ ./
docker rm tmp-rpi-rt-linux
tmp-rpi-rt-linux
```

There will be an image (zip) of size 552MiB in the `build` folder and it even works on my Pi zero, but I don't get the expected kernel, which is kinda funny and I don't understand it:

```
$ uname -a
Linux poozero 6.1.21+ #1642 Mon Apr  3 17:19:14 BST 2023 armv6l GNU/Linux
```

Where did it get the 6.1.21 kernel from when I built everything for 5.15.92?????

I also tried cloning the repo multiple times and removing the used docker image(s) as well.

**Comment by houserockr** [comment]
I managed to make it work.

I changed `build.sh`

from 

`cp /rpi-kernel/linux/arch/arm/boot/zImage /raspios/mnt/boot/$KERNEL\_rt.img`
to
`cp /rpi-kernel/linux/arch/arm/boot/Image /raspios/mnt/boot/$KERNEL\_rt.img`

within the `elif [ "$ARCH" = "arm" ]; then` path.

No idea tho why in my case the image is called `Image` instead of `zImage`.

**Comment by remusmp** [comment]
Should be fixed now in the latest commit. Let me know if you see more issues with it.
