### ISSUE TITLE
Raspberry Pi 5 support?

### ISSUE THREAD

**Issue by amyodov** [remusmp/rpi-rt-kernel#17]
Crossing the fingers to see the Raspberry Pi 5 support here... `Pi5` is not in the options in the Makefile, but hopefully it can be just added together with the Pi4, in a line like `Pi3 Pi4 Pi5 Pi400 PiZero2 PiCM3 PiCM4: clean`, and mentioned in the readme.

I actually tried to use this build script without the changes, and was able to at least build the resulting `kernel8_rt.img` (I didn't use the img SD card image file directly, but copied just the kernel files – your script is still the best one to build the RT RPi kernel in a docker/on a more powerful station, even if one just needs the kernel, not the whole SD card image), and that resulted in a `Linux raspberrypi 6.6.31-v8+ #1 SMP` without any RT, so some other tweaks may be required, too.

Also, it would be highly appreciated if you could give some hints in readme/add some extra lines in a Makefile, to avoid building the SD card image, just cross-building the kernel image (for further transfer to a live system).

**Comment by remusmp** [comment]
There was an issue with the RT patch and I just pushed a fix for it. It should build ok now with the RT patch applied.
I haven't tested on a raspberry pi 5 yet (only CM4). I'll get a pi 5 soon and test everything.

**Comment by remusmp** [comment]
I've just checked the docs on Pi5 and there are a few additional changes to add to the build. I will have it done by the end of the week.

**Comment by remusmp** [comment]
Pi5 should work now. `make Pi5` or just `make` should build it. I made Pi5 the default platform.
