### ISSUE TITLE
rt-kernel not used

### ISSUE THREAD

**Issue by helander** [remusmp/rpi-rt-kernel#19]
I have built an image for Pi4 and I can find the built files under /boot, but the system is not booted using the built kernel. 
uname -a shows that a non-rt kernel is in use.
What do I need to do to make the image boot the rt-kernel?

**Comment by Buyingbf** [comment]
I had the same issue and I resolved it on my end by modifying the Dockerfile and replacing any instance of {PATCH} with {LINUX_KERNEL_RT_PATCH}.

**Comment by helander** [comment]
Thank you very much.  I will test this and report back.

**Comment by helander** [comment]
Now tested and it worked 😃

**Comment by helander** [comment]
Closing

**Comment by remusmp** [comment]
I confirm this was a bug and it's now fixed in the repo as well.
