### ISSUE TITLE
Parametrize the build with kernel version and rt patch version

### ISSUE THREAD

**Issue by remusmp** [remusmp/rpi-rt-kernel#2]
Arguments:
1. Kernel version (e.g. KERNEL_VERSION=5.10). If argument is missing then default to latest.
2. RT patch version (e.g. RT_PATCH_VERSION=rt54). If argument is missing then default to latest.

**Comment by jakorten** [comment]
Current file is broken because of this:
patch-5.10.73-rt54.patch.gz -> patch-5.10.78-rt55.patch.gz

**Comment by remusmp** [comment]
Thanks for the contributions! Much appreciated!

One more thing needs to be done, i.e. update the .config file with the right settings. One cannot use a .config file from an older version with a newer version. I tried that a few weeks ago and the kernel, although it built, was not fully preempt - I had to regenerate the .config file. So my proposal here is to:
- remove .config from this repo and don't add it to the docker image anymore
- Dockerfile: use `sed` to disable `KVM` in .config
- Dockerfile: use `sed` to enable the RT PATCH

**Comment by remusmp** [comment]
I've just pushed the following work on this:
- download latest RT patch for a given linux kernel version - it shouldn't break the build anymore when new rt patches are released
- download latest raspbian as well by default

TO DO:
- let the user specify a certain RT patch and a certain raspbian version (check the PR)
