### ISSUE TITLE
Start from arm64 rpi images instead of armhf

### ISSUE THREAD

**Issue by matteosacchetto** [remusmp/rpi-rt-kernel#4]
I was thinking, given that the build is targeted towards arm64, and since now the rpi arm64 images are out of beta, why not using the arm64 images as base image instead of the armhf ones?

It should be easy to do, since it should be necessary to only change all the "armhf" to "arm64" whenever it comes to the image portion of the Docker file

https://github.com/remusmp/rpi-rt-kernel/blob/f1b8c889d20a62409ac0c9deced70ecd0fca119a/Dockerfile#L37-L41

So, I just wanted to know your thoughts on this and if you had any reason to use the armhf base images instead of the arm64 ones.

Best,
Matteo

**Comment by remusmp** [comment]
Hi Matteo,

Yes, definitely we can switch to arm64. I will do a test and check that everything still builds fine with arm64 and change it.

Thanks for pointing out that they released the arm64.

Best regards,
Remus.

**Comment by remusmp** [comment]
I've just pushed a new commit with the `arm64` change + some extra docs. I tested on my pi and everything should build and run ok.
